### ISSUE TITLE
RFC: Add i18n support

### ISSUE THREAD

**Issue by avivace** [gbadev-org/tonc#67]
Could localized versions of TONC be useful?

See: https://github.com/google/mdbook-i18n-helpers

**Comment by copyrat90** [comment]
Maybe I can translate TONC into Korean at some point if we have this.
Not in near future though.

**Comment by exelotl** [comment]
Responding to query from avivace on discord:

hmm, I don't think localisation itself is useful at this point - given that it's a _colossal_ amount of work we'd want to avoid it while the English content is still subject to major changes, otherwise we'd risk obsoleting translators' work.

I noticed the .po files in [gb-asm-tutorial](https://github.com/gbdev/gb-asm-tutorial) seem to treat the original English text as the 'key' for each translated paragraph - how does that work for minor English adjustments? Do you have to re-export the whole translation each time?

Enabling the ability to do translation could be fine as long as it doesn't lead to the above problems, but personally I'd be inclined to wait or just leave a note in the readme saying "interested in translating? get in touch!" for now.

**Comment by avivace** [comment]
Agree, doesn't make a lot of sense to start translating now when we're actually looking for ovehauls and general major improvements.

@exelotl in gb-asm-tutorial an mdbook plugin extracts all the po strings for you automatically so it's pretty transparent. When a string changes you'll just see it as "outdated" in the translation software and that will need to be translated again (will be shown as the original language until that happens)
